# Generated by Django 4.2.6 on 2024-04-29 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_producto', models.IntegerField(choices=[(1, 'Herramientas Manuales'), (2, 'Materiales Basicos'), (3, 'Equipo de Seguridad'), (4, 'Tornillos y Anclajes'), (5, 'Fijaciones y Adhesivos'), (6, 'Equipos de Medicion')])),
                ('nombre', models.CharField(max_length=25, unique=True)),
                ('precio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999)])),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
